name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
    FLET_DIST_DIR: dist
    PYODIDE_VERSION: 0.23.2

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v4
            with:
                python-version: '3.11'
          - name: Install flet
            run: pip install flet

          - uses: actions/setup-java@v1
            with:
              java-version: "8.x"
          - uses: subosito/flutter-action@v1
            with:
              channel: 'stable'            
          - name: Build patched flet web
            run: |
                git clone https://github.com/liudonghua123/flet.git -b file_picker_bytes
                cd flet/client
                flutter pub get
                flutter build web
                cp -r build/web ../../web
                cd ../..
                python .github/workflows/patch_flet_web.py web

          - name: build for web platform
            run: |
                # GITHUB_REPOSITORY={{github.repository}}
                echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, user: ${GITHUB_REPOSITORY%/*}, project: ${GITHUB_REPOSITORY#*/}"
                flet publish --base-url ${GITHUB_REPOSITORY#*/} main.py
          - name: use self-hosted pyodide
            run: |
                wget https://github.com/pyodide/pyodide/releases/download/${{env.PYODIDE_VERSION}}/pyodide-${{env.PYODIDE_VERSION}}.tar.bz2
                tar -xvf pyodide-${{env.PYODIDE_VERSION}}.tar.bz2 -C dist
                sed -i 's#http.*pyodide.js#pyodide/pyodide.js#g' dist/python-worker.js
                cat dist/python-worker.js
          - name: patch python-worker.js to use customized flet-core
            run: |
                cp .github/workflows/flet_core-0.7.4-py3-none-any.whl dist/pyodide
                patch dist/python-worker.js < .github/workflows/python-worker.js.patch
                cat dist/python-worker.js
          - name: check flet publish build files on ${{env.FLET_DIST_DIR}}
            run: |
              ls -la ${{env.FLET_DIST_DIR}}
          - name: Deploy to GitHub Pages 🚀
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: ${{env.FLET_DIST_DIR}}